sql:
  select-recipients-query: select email from &monitoring_recipients where comm_coverage = 1;
  select-offer-info-query: >-
    SELECT * FROM dblink(
      'sa_remote',
      '
      select ''test'', 1, 1, 1, 1, 1, 1'
    ) as t (metric_name varchar, gz_sms int8, gz_email int8, "366_sms" int8, "366_email" int8, kf_sms int8, kf_email int8);
  select-offer-info-query-old: >-
    with all_block_gcg as (
      SELECT * FROM dblink(
        'sa_remote',
        $$
        select cre_card_pan_num
        from sa_act_block_gcg_dwh
        $$
      ) AS t ( cre_card_pan_num FLOAT8)
      )
      ,
      sms as (
          select 
              count(cu.cre_card_pan_num),
              count(distinct cu.cre_card_pan_num) as dcount,
              case 
                  when mch.campaign_nm like '%ИНФО%' then 'Инфо'
                  else 'Оффер'
              end as class,
              case 
                  when mch.status like 'UNDELIV%' then 'Не успешно'
                  else 'Успешно'
              end as Dstatus,
              substring(cu.cre_card_pan_num::text, 0, 4) as card_prefix
          from 
              cdm.v_contact_history mch
          join 
              cmdm.card_united cu on mch.cre_card_id = cu.cre_card_id
          where 
              channel = 'Каскадная рассылка'
              and date(contact_dttm) >= date_trunc('month', current_date)
              and date(contact_dttm) < date_trunc('month', current_date) + interval '1 month'
              and substring(cu.cre_card_pan_num::text, 0, 4) in ('300', '366', '350')
          group by 
              class, Dstatus, card_prefix
      ),
      email as (
          select 
              count(cu.cre_card_pan_num),
              count(distinct cu.cre_card_pan_num) as dcount,
              case 
                  when mch.campaign_nm like '%ИНФО%' then 'Инфо'
                  else 'Оффер'
              end as class,
              case 
                  when mch.status like 'DELIV%' then 'Успешно'
                  else 'Не успешно'
              end as Dstatus,
              substring(cu.cre_card_pan_num::text, 0, 4) as card_prefix
          from 
              cdm.v_contact_history mch
          join 
              cmdm.card_united cu on mch.cre_card_id = cu.cre_card_id
          where 
              channel = 'Email SendSay'
              and date(contact_dttm) >= date_trunc('month', current_date)
              and date(contact_dttm) < date_trunc('month', current_date) + interval '1 month'
              and substring(cu.cre_card_pan_num::text, 0, 4) in ('300', '366', '350')
          group by 
              class, Dstatus, card_prefix
      )
    select
        'Count_offer' as metric_name,
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.count end) as "GZ_sms",
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.count end) as "GZ_email",
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.count end) as "366_sms",
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.count end) as "366_email",
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.count end) as "KF_sms",
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.count end) as "KF_email"
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    union all
    select
        'GZ_DCount_offer',
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.dcount end),
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.dcount end),
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Успешно' and e1.class = 'Оффер' then e1.dcount end)
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    union all
    select
        'DCount_undel_offer',
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Не успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Не успешно' and e1.class = 'Оффер' then e1.dcount end),
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Не успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Не успешно' and e1.class = 'Оффер' then e1.dcount end),
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Не успешно' and q1.class = 'Оффер' then q1.dcount end),
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Не успешно' and e1.class = 'Оффер' then e1.dcount end)
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    union all 
    select 
        'Count_info' as metric_name,
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.count end) as "GZ_sms",
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.count end) as "GZ_email",
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.count end) as "366_sms",
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.count end) as "366_email",
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.count end) as "KF_sms",
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.count end) as "KF_email"
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    union all
    select
        'DCount_info',
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.dcount end),
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.dcount end),
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Успешно' and e1.class = 'Инфо' then e1.dcount end)
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    union all
    select
        'DCount_undel_info',
        max(case when q1.card_prefix = '300' and q1.Dstatus = 'Не успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '300' and e1.Dstatus = 'Не успешно' and e1.class = 'Инфо' then e1.dcount end),
        max(case when q1.card_prefix = '366' and q1.Dstatus = 'Не успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '366' and e1.Dstatus = 'Не успешно' and e1.class = 'Инфо' then e1.dcount end),
        max(case when q1.card_prefix = '350' and q1.Dstatus = 'Не успешно' and q1.class = 'Инфо' then q1.dcount end),
        max(case when e1.card_prefix = '350' and e1.Dstatus = 'Не успешно' and e1.class = 'Инфо' then e1.dcount end)
    from 
        sms q1
    left join
        email e1 on q1.card_prefix = e1.card_prefix 
    ;